### ISSUE TITLE
Exception 0xc0000005 0x0 0xffffffffffffffff 0x7fef531a5b8

### ISSUE THREAD

**Issue by Martin2877** [chaitin/xray#497]
我很奇怪，总会有这样的报错。

```
Exception 0xc0000005 0x0 0xffffffffffffffff 0x7fef531a5b8
PC=0x7fef531a5b8

syscall.Syscall9(0x7feff1c13b0, 0x7, 0x85c, 0xc000f4e138, 0x1, 0xc000f4e120, 0x0
, 0xc000f4e0f0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/syscall_windows.go:210 +0xfa
syscall.WSASend(0x85c, 0xc000f4e138, 0x1, 0xc000f4e120, 0x0, 0xc000f4e0f0, 0x0,
0x0, 0x0)
        /usr/local/go/src/syscall/zsyscall_windows.go:1577 +0xf2
internal/poll.(*FD).Write.func1(0xc000f4e0f0, 0x77, 0xc00182d400)
        /usr/local/go/src/internal/poll/fd_windows.go:724 +0x6a
internal/poll.(*ioSrv).ExecIO(0x20a3d60, 0xc000f4e0f0, 0x13aeeb0, 0xc001969670,
0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_windows.go:206 +0xbb
internal/poll.(*FD).Write(0xc000f4e000, 0xc00326f000, 0x736, 0x1000, 0x0, 0x0, 0
x0)
        /usr/local/go/src/internal/poll/fd_windows.go:723 +0x338
net.(*netFD).Write(0xc000f4e000, 0xc00326f000, 0x736, 0x1000, 0x6b, 0x18, 0xc)
        /usr/local/go/src/net/fd_windows.go:164 +0x56
net.(*conn).Write(0xc002113048, 0xc00326f000, 0x736, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:196 +0x6f
net/http.persistConnWriter.Write(0xc001903560, 0xc00326f000, 0x736, 0x1000, 0x10
83b00, 0xc001755c30, 0x1083b00)
        /usr/local/go/src/net/http/transport.go:1582 +0x59
bufio.(*Writer).Flush(0xc00226d040, 0x150e060, 0xc00226d040)
        /usr/local/go/src/bufio/bufio.go:593 +0x7c
net/http.(*persistConn).writeLoop(0xc001903560)
        /usr/local/go/src/net/http/transport.go:2212 +0x39f
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1567 +0xb2a

goroutine 1 [select]:
gunkit/core/assassin/utils.(*SizedWaitGroup).AddWithContext(0xc002d5de90, 0x152e
380, 0xc002537800, 0x1, 0x11bae00)
        /builds/lohengrin/gunkit/core/assassin/utils/sync.go:34 +0xcc
gunkit/core/assassin/controller.(*unit).run(0xc002d5de60, 0x152e380, 0xc00253780
0, 0x152e700, 0xc001104e10, 0xc0018fc3e0, 0x0, 0x0)
        /builds/lohengrin/gunkit/core/assassin/controller/controller.go:34 +0xe3

gunkit/core/assassin/controller.(*SingleProcessController).Start(0xc0024b6120, 0
x152e380, 0xc002537800, 0x10, 0x0)
        /builds/lohengrin/gunkit/core/assassin/controller/single.go:189 +0x483
gunkit/core/assassin/cli.glob..func3(0xc000f52840, 0x0, 0x0)
        /builds/lohengrin/gunkit/core/assassin/cli/webscan.go:365 +0x8db
github.com/urfave/cli.HandleAction(0x109fde0, 0x13aea78, 0xc000f52840, 0xc00209e
d00, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xcf
github.com/urfave/cli.Command.Run(0x12a7f21, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x12b
6095, 0x12, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x998
github.com/urfave/cli.(*App).Run(0xc00197c340, 0xc0000ac000, 0x6, 0x8, 0x0, 0x0)

        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x6b2
main.main()
        /builds/lohengrin/gunkit/core/assassin/main.go:82 +0x287

goroutine 6 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0xa3
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x29
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x48

goroutine 10606 [select]:
net/http.(*persistConn).writeLoop(0xc001778ea0)
        /usr/local/go/src/net/http/transport.go:2196 +0x12a
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:
```

**Comment by virusdefender** [comment]
你好，这个报错信息是完整的么，感觉缺一些东西

**Comment by zema1** [comment]
请在新版试下。另外，提交 panic 信息请提交完整的，太大可以作为文件上传。

**Comment by Martin2877** [comment]
好的，我整理一下。

**Comment by virusdefender** [comment]
不知道为啥，先 close 了，如果可以复现或者我们有什么进展，可以在这 issue 中交流。
