### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shmilylty** [chaitin/xray#534]
```bash
# uname -a
Linux iZbp1echzpb2gsZ 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
运行的命令：./xray_linux_amd64 webscan --listen 0.0.0.0:9527 --html-output test.html --json-output test.json --webhook-output http://127.0.0.1:5000/webhook

VPS上部署xray 跑了一会儿挂了 好像是内存地址的问题
```
Mitm: pending: 51, capacity: 1000000
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xcea0cf]

goroutine 10854 [running]:
sync.(*RWMutex).RLock(...)
	/usr/local/go/src/sync/rwmutex.go:48
github.com/zema1/martian.(*Session).Get(0x0, 0x1303a8d, 0xc, 0x0, 0x0, 0x2193c00)
	/go/pkg/mod/github.com/zema1/martian@v0.0.0-20190815085251-5b7efe2beb30/context.go:170 +0x3f
github.com/zema1/martian/auth.FromContext(0xc002732fc0, 0xc002732fc0)
	/go/pkg/mod/github.com/zema1/martian@v0.0.0-20190815085251-5b7efe2beb30/auth/context.go:34 +0x47
github.com/zema1/martian/proxyauth.(*Modifier).ModifyResponse(0xc00354b980, 0xc0087f26c0, 0xc003079650, 0x1)
	/go/pkg/mod/github.com/zema1/martian@v0.0.0-20190815085251-5b7efe2beb30/proxyauth/proxyauth.go:87 +0x44
github.com/zema1/martian/fifo.(*Group).ModifyResponse(0xc003798ee0, 0xc0087f26c0, 0x0, 0x0)
	/go/pkg/mod/github.com/zema1/martian@v0.0.0-20190815085251-5b7efe2beb30/fifo/fifo_group.go:132 +0x111
github.com/zema1/martian.(*Proxy).handle(0xc002d6a4d0, 0xc002732600, 0x15a1ca0, 0xc00121df88, 0xc00878c1f0, 0x0, 0x0)
	/go/pkg/mod/github.com/zema1/martian@v0.0.0-20190815085251-5b7efe2beb30/proxy.go:472 +0x7d1
github.com/zema1/martian.(*Proxy).handleLoop(0xc002d6a4d0, 0x15a1ca0, 0xc00121df88)
	/go/pkg/mod/github.com/zema1/martian@v0.0.0-20190815085251-5b7efe2beb30/proxy.go:250 +0x433
created by github.com/zema1/martian.(*Proxy).Serve
	/go/pkg/mod/github.com/zema1/martian@v0.0.0-20190815085251-5b7efe2beb30/proxy.go:218 +0x353
```

**Comment by shmilylty** [comment]
![image](https://user-images.githubusercontent.com/24275308/68097037-96135900-feef-11e9-8a33-890824b4687e.png)

**Comment by virusdefender** [comment]
不知道为啥，先 close 了，如果可以复现或者我们有什么进展，可以在这 issue 中交流。
