### ISSUE TITLE
1.4版本无法使用--basic-crawler

### ISSUE THREAD

**Issue by fngoo** [chaitin/xray#923]
**命令**
```
xray_windows_amd64.exe webscan --basic-crawler testphp.vulnweb.com --json-output 123.txt
```
**报错**
```
[INFO] 2020-11-09 17:14:45 [basic-crawler:basic_crawler.go:78] crawler stopped
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0xcab1b5]

goroutine 1 [running]:
gunkit/core/utils/printer.(*BasePrinter).writeWithSync(0xc00050d320, 0xc000357ab2, 0x2, 0x2, 0x58b5e8, 0x108f623)
        /builds/lohengrin/gunkit/core/utils/printer/base.go:103 +0x35
gunkit/core/utils/printer.(*BasePrinter).Close(0xc00050d320, 0x0, 0x0)
        /builds/lohengrin/gunkit/core/utils/printer/base.go:94 +0xda
gunkit/core/utils/printer.(*MultiPrinter).Close(0xc0000d1d40, 0x0, 0x0)
        /builds/lohengrin/gunkit/core/utils/printer/multi.go:62 +0xf0
gunkit/core/assassin/ctrl.(*Dispatcher).Release(0xc0001b1ad0)
        /builds/lohengrin/gunkit/core/assassin/ctrl/dispatcher.go:526 +0xa4
gunkit/core/assassin/entry.glob..func3(0xc0003031e0, 0x0, 0x0)
        /builds/lohengrin/gunkit/core/assassin/entry/webscan.go:263 +0xf69
github.com/urfave/cli.HandleAction(0x146bea0, 0x22100c0, 0xc0003031e0, 0xc000682000, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xcf
github.com/urfave/cli.Command.Run(0x1733d91, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0x17449d5, 0x12, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x9ef
github.com/urfave/cli.(*App).Run(0xc00023aea0, 0xc0000d2000, 0x6, 0x8, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x748
main.main()
        /builds/lohengrin/gunkit/core/assassin/main.go:106 +0x27f
```

**Comment by zema1** [comment]
今天发版解决

**Comment by zema1** [comment]
1.4.2 已修复
